export * from "./users";
export * from "./facturas";
export * from "./proveedores";
export * from "./tipos-operacion";
export * from "./tipos-propiedad";
export * from "./proyectos";
export * from "./parte-diario";
export * from "./departamentos";
export * from "./tipos-solicitud";
export * from "./solicitudes";
export * from "./centros-costo";
export * from "./propiedades";
export * from "./vacancias";
export * from "./crm-catalogos/crm-catalogos-tipos-operacion";
export * from "./crm-catalogos/crm-catalogos-motivos-perdida";
export * from "./crm-catalogos/crm-catalogos-condiciones-pago";
export * from "./crm-catalogos/crm-catalogos-tipos-evento";
export * from "./crm-catalogos/crm-catalogos-motivos-evento";
export * from "./crm-catalogos/crm-catalogos-origenes-lead";
export * from "./monedas";
export * from "./crm-cotizaciones";
export * from "./crm-contactos";
export * from "./crm-oportunidades";
export * from "./crm-eventos";
export * from "./crm-chat";
export * from "./crm-mensajes";
export * from "./emprendimientos";
// Los dashboards no necesitan ser exportados aqu??
// export * from "./dashboard-proyectos";
// export * from "./dashboard-vacancias";
