export * from "./users";
export * from "./facturas";
export * from "./proveedores";
export * from "./tipos-operacion";
export * from "./tipos-propiedad";
export * from "./proyectos";
export * from "./parte-diario";
export * from "./departamentos";
export * from "./tipos-solicitud";
export * from "./po/po-orders";
export * from "./po/po-order-status";
export * from "./po/po-invoice-status";
export * from "./po/po-invoice-status-fin";
export * from "./centros-costo";
export * from "./tipos-articulo";
export * from "./propiedades";
export * from "./inmobiliaria";
export * from "./vacancias";
export * from "./crm-catalogos/crm-catalogos-tipos-operacion";
export * from "./crm-catalogos/crm-catalogos-motivos-perdida";
export * from "./crm-catalogos/crm-catalogos-condiciones-pago";
export * from "./crm-catalogos/crm-catalogos-tipos-evento";
export * from "./crm-catalogos/crm-catalogos-motivos-evento";
export * from "./crm-catalogos/crm-catalogos-respuestas";
export * from "./monedas";
export * from "./crm-cotizaciones";
export * from "./crm-contactos";
export * from "./crm-oportunidades";
export * from "./crm-eventos";
export * from "./crm-chat";
export * from "./crm-mensajes";
export * from "./emprendimientos";
export * from "./calculadora-financiera";
export * from "./adm-conceptos";
export * from "./tax-profiles";
// Los dashboards no necesitan ser exportados aquí
// export * from "./dashboard-proyectos";
// export * from "./dashboard-vacancias";
