"""verification_check

Revision ID: 103a99b6faf9
Revises: 5b42ffe84032
Create Date: 2026-01-11 18:45:31.594305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '103a99b6faf9'
down_revision: Union[str, Sequence[str], None] = '5b42ffe84032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adm_conceptos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('adm_conceptos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('adm_conceptos', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint('uq_cotizacion_moneda_fecha', 'cotizacion_moneda', type_='unique')
    op.create_unique_constraint('uq_cotizacion_monedas_fecha', 'cotizacion_moneda', ['moneda_origen_id', 'moneda_destino_id', 'fecha_vigencia'])
    op.alter_column('crm_catalogo_respuestas', 'texto',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('crm_celulares', 'numero_celular',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('crm_celulares_meta_celular_id_key', 'crm_celulares', type_='unique')
    op.drop_index('ix_crm_celulares_activo', table_name='crm_celulares')
    op.drop_index('ix_crm_celulares_meta_celular_id', table_name='crm_celulares')
    op.create_index(op.f('ix_crm_celulares_meta_celular_id'), 'crm_celulares', ['meta_celular_id'], unique=True)
    op.alter_column('crm_eventos', 'oportunidad_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('crm_eventos', 'titulo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('crm_eventos', 'resultado',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_column('crm_eventos', 'fecha_compromiso')
    op.drop_column('crm_eventos', 'proximo_paso')
    op.alter_column('crm_mensajes', 'contenido',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_column('crm_mensajes', 'metadata_json')
    op.alter_column('crm_oportunidades', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_column('crm_oportunidades', 'cotizacion_aplicada')
    op.alter_column('departamentos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('departamentos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('departamentos', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint('departamentos_nombre_key', 'departamentos', type_='unique')
    op.drop_index('ix_departamentos_nombre', table_name='departamentos')
    op.create_index(op.f('ix_departamentos_nombre'), 'departamentos', ['nombre'], unique=True)
    op.drop_constraint('fk_nominas_proyectos_idproyecto', 'nominas', type_='foreignkey')
    op.create_foreign_key(None, 'nominas', 'proyectos', ['idproyecto'], ['id'])
    op.alter_column('po_factura_detalles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_factura_detalles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_factura_detalles', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_foreign_key(None, 'po_factura_detalles', 'centros_costo', ['centro_costo_id'], ['id'])
    op.alter_column('po_factura_impuestos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_factura_impuestos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_factura_impuestos', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('po_facturas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_facturas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_facturas', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('po_facturas', 'observaciones',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.create_foreign_key(None, 'po_facturas', 'tipos_solicitud', ['tipo_solicitud_id'], ['id'])
    op.create_foreign_key(None, 'po_facturas', 'centros_costo', ['centro_costo_id'], ['id'])
    op.alter_column('po_orden_compra_detalles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_orden_compra_detalles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_orden_compra_detalles', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_foreign_key(None, 'po_orden_compra_detalles', 'centros_costo', ['centro_costo_id'], ['id'])
    op.alter_column('po_ordenes_compra', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_ordenes_compra', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_ordenes_compra', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('po_ordenes_compra', 'observaciones',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('po_solicitud_detalles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_solicitud_detalles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_solicitud_detalles', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('po_solicitudes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_solicitudes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_solicitudes', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('proyectos', 'comentario',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('tipos_solicitud', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tipos_solicitud', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('tipos_solicitud', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint('tipos_solicitud_nombre_key', 'tipos_solicitud', type_='unique')
    op.drop_index('ix_tipos_solicitud_nombre', table_name='tipos_solicitud')
    op.create_index(op.f('ix_tipos_solicitud_nombre'), 'tipos_solicitud', ['nombre'], unique=True)
    op.drop_index('ix_webhook_logs_created_at', table_name='webhook_logs')
    op.drop_index('ix_webhook_logs_procesado', table_name='webhook_logs')
    op.create_index(op.f('ix_webhook_logs_fecha_recepcion'), 'webhook_logs', ['fecha_recepcion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_logs_fecha_recepcion'), table_name='webhook_logs')
    op.create_index('ix_webhook_logs_procesado', 'webhook_logs', ['procesado'], unique=False)
    op.create_index('ix_webhook_logs_created_at', 'webhook_logs', ['created_at'], unique=False)
    op.drop_index(op.f('ix_tipos_solicitud_nombre'), table_name='tipos_solicitud')
    op.create_index('ix_tipos_solicitud_nombre', 'tipos_solicitud', ['nombre'], unique=False)
    op.create_unique_constraint('tipos_solicitud_nombre_key', 'tipos_solicitud', ['nombre'])
    op.alter_column('tipos_solicitud', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('tipos_solicitud', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tipos_solicitud', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('proyectos', 'comentario',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('po_solicitudes', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('po_solicitudes', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_solicitudes', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_solicitud_detalles', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('po_solicitud_detalles', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_solicitud_detalles', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_ordenes_compra', 'observaciones',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('po_ordenes_compra', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('po_ordenes_compra', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_ordenes_compra', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'po_orden_compra_detalles', type_='foreignkey')
    op.alter_column('po_orden_compra_detalles', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('po_orden_compra_detalles', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_orden_compra_detalles', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'po_facturas', type_='foreignkey')
    op.drop_constraint(None, 'po_facturas', type_='foreignkey')
    op.alter_column('po_facturas', 'observaciones',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('po_facturas', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('po_facturas', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_facturas', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_factura_impuestos', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('po_factura_impuestos', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_factura_impuestos', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'po_factura_detalles', type_='foreignkey')
    op.alter_column('po_factura_detalles', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('po_factura_detalles', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_factura_detalles', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'nominas', type_='foreignkey')
    op.create_foreign_key('fk_nominas_proyectos_idproyecto', 'nominas', 'proyectos', ['idproyecto'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_departamentos_nombre'), table_name='departamentos')
    op.create_index('ix_departamentos_nombre', 'departamentos', ['nombre'], unique=False)
    op.create_unique_constraint('departamentos_nombre_key', 'departamentos', ['nombre'])
    op.alter_column('departamentos', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('departamentos', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('departamentos', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('crm_oportunidades', sa.Column('cotizacion_aplicada', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=True))
    op.alter_column('crm_oportunidades', 'descripcion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('crm_mensajes', sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('crm_mensajes', 'contenido',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('crm_eventos', sa.Column('proximo_paso', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('crm_eventos', sa.Column('fecha_compromiso', sa.DATE(), autoincrement=False, nullable=True))
    op.alter_column('crm_eventos', 'resultado',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('crm_eventos', 'titulo',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('crm_eventos', 'oportunidad_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_crm_celulares_meta_celular_id'), table_name='crm_celulares')
    op.create_index('ix_crm_celulares_meta_celular_id', 'crm_celulares', ['meta_celular_id'], unique=False)
    op.create_index('ix_crm_celulares_activo', 'crm_celulares', ['activo'], unique=False)
    op.create_unique_constraint('crm_celulares_meta_celular_id_key', 'crm_celulares', ['meta_celular_id'])
    op.alter_column('crm_celulares', 'numero_celular',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('crm_catalogo_respuestas', 'texto',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_cotizacion_monedas_fecha', 'cotizacion_moneda', type_='unique')
    op.create_unique_constraint('uq_cotizacion_moneda_fecha', 'cotizacion_moneda', ['moneda_origen_id', 'moneda_destino_id', 'fecha_vigencia'])
    op.alter_column('adm_conceptos', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('adm_conceptos', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('adm_conceptos', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
