"""add_proyecto_fields_and_avance_table

Revision ID: 200540588e7f
Revises: 20260318_keep_closed_opportunities_active
Create Date: 2026-03-19 18:55:14.854922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '200540588e7f'
down_revision: Union[str, Sequence[str], None] = '20260318_keep_closed_opportunities_active'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create proyecto_avance table
    op.create_table('proyecto_avance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('horas', sa.Integer(), nullable=False),
    sa.Column('avance', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('comentario', sa.String(), nullable=True),
    sa.Column('fecha_registracion', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Add new columns to proyectos table
    op.add_column('proyectos', sa.Column('centro_costo', sa.Integer(), nullable=True))
    op.add_column('proyectos', sa.Column('terceros', sa.DECIMAL(precision=14, scale=2), server_default='0', nullable=False))
    op.add_column('proyectos', sa.Column('herramientas', sa.DECIMAL(precision=14, scale=2), server_default='0', nullable=False))
    op.add_column('proyectos', sa.Column('superficie', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('proyectos', sa.Column('ingresos', sa.DECIMAL(precision=14, scale=2), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Remove columns added to proyectos table
    op.drop_column('proyectos', 'ingresos')
    op.drop_column('proyectos', 'superficie')
    op.drop_column('proyectos', 'herramientas') 
    op.drop_column('proyectos', 'terceros')
    op.drop_column('proyectos', 'centro_costo')
    
    # Drop proyecto_avance table
    op.drop_table('proyecto_avance')
