"""add_fecha_estado_to_crm_mensajes

Revision ID: 3fe6ede299ac
Revises: 023_add_descripcion_eventos
Create Date: 2025-12-04 16:30:31.702079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fe6ede299ac'
down_revision: Union[str, Sequence[str], None] = '023_add_descripcion_eventos'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('propiedades_backup_20251116_231115')
    op.drop_table('vacancias_backup_20251116_231630')
    op.drop_table('propiedades_backup_20251116_231630')
    op.drop_table('vacancias_backup_20251116_231115')
    op.drop_constraint('uq_cotizacion_moneda_fecha', 'cotizacion_moneda', type_='unique')
    op.create_unique_constraint('uq_cotizacion_monedas_fecha', 'cotizacion_moneda', ['moneda_origen_id', 'moneda_destino_id', 'fecha_vigencia'])
    op.drop_index('idx_contacto_estado_calificacion', table_name='crm_contactos')
    op.drop_constraint('fk_crm_contactos_tipo_operacion_interes', 'crm_contactos', type_='foreignkey')
    op.drop_column('crm_contactos', 'estado_calificacion')
    op.drop_column('crm_contactos', 'tipo_operacion_interes_id')
    op.drop_column('crm_contactos', 'necesidad')
    op.alter_column('crm_eventos', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('crm_eventos', 'resultado',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_index('idx_crm_eventos_estado', table_name='crm_eventos', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_crm_eventos_oportunidad', table_name='crm_eventos', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_crm_eventos_tipo', table_name='crm_eventos', postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_crm_eventos_tipo_evento'), 'crm_eventos', ['tipo_evento'], unique=False)
    op.add_column('crm_mensajes', sa.Column('fecha_estado', sa.DateTime(), nullable=True))
    
    # Inicializar fecha_estado con fecha_mensaje para registros existentes
    op.execute("""
        UPDATE crm_mensajes 
        SET fecha_estado = fecha_mensaje 
        WHERE fecha_estado IS NULL
    """)
    
    op.alter_column('crm_mensajes', 'contenido',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('crm_mensajes', 'fecha_mensaje',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index('idx_crm_mensajes_canal_ref', table_name='crm_mensajes')
    op.drop_index('idx_crm_mensajes_contacto', table_name='crm_mensajes')
    op.drop_index('idx_crm_mensajes_estado_tipo', table_name='crm_mensajes')
    op.drop_index('idx_crm_mensajes_evento', table_name='crm_mensajes')
    op.create_index(op.f('ix_crm_mensajes_canal'), 'crm_mensajes', ['canal'], unique=False)
    op.create_index(op.f('ix_crm_mensajes_contacto_id'), 'crm_mensajes', ['contacto_id'], unique=False)
    op.create_index(op.f('ix_crm_mensajes_contacto_referencia'), 'crm_mensajes', ['contacto_referencia'], unique=False)
    op.create_index(op.f('ix_crm_mensajes_estado'), 'crm_mensajes', ['estado'], unique=False)
    op.create_index(op.f('ix_crm_mensajes_evento_id'), 'crm_mensajes', ['evento_id'], unique=False)
    op.create_index(op.f('ix_crm_mensajes_fecha_estado'), 'crm_mensajes', ['fecha_estado'], unique=False)
    op.create_index(op.f('ix_crm_mensajes_origen_externo_id'), 'crm_mensajes', ['origen_externo_id'], unique=False)
    op.create_index(op.f('ix_crm_mensajes_prioridad'), 'crm_mensajes', ['prioridad'], unique=False)
    op.create_index(op.f('ix_crm_mensajes_responsable_id'), 'crm_mensajes', ['responsable_id'], unique=False)
    op.create_index(op.f('ix_crm_mensajes_tipo'), 'crm_mensajes', ['tipo'], unique=False)
    op.drop_constraint('fk_crm_mensajes_oportunidad_id', 'crm_mensajes', type_='foreignkey')
    op.create_foreign_key(None, 'crm_mensajes', 'crm_oportunidades', ['oportunidad_id'], ['id'])
    op.drop_index('idx_oportunidad_activo', table_name='crm_oportunidades')
    op.create_index(op.f('ix_crm_oportunidades_activo'), 'crm_oportunidades', ['activo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_oportunidades_activo'), table_name='crm_oportunidades')
    op.create_index('idx_oportunidad_activo', 'crm_oportunidades', ['activo'], unique=False)
    op.drop_constraint(None, 'crm_mensajes', type_='foreignkey')
    op.create_foreign_key('fk_crm_mensajes_oportunidad_id', 'crm_mensajes', 'crm_oportunidades', ['oportunidad_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_crm_mensajes_tipo'), table_name='crm_mensajes')
    op.drop_index(op.f('ix_crm_mensajes_responsable_id'), table_name='crm_mensajes')
    op.drop_index(op.f('ix_crm_mensajes_prioridad'), table_name='crm_mensajes')
    op.drop_index(op.f('ix_crm_mensajes_origen_externo_id'), table_name='crm_mensajes')
    op.drop_index(op.f('ix_crm_mensajes_fecha_estado'), table_name='crm_mensajes')
    op.drop_index(op.f('ix_crm_mensajes_evento_id'), table_name='crm_mensajes')
    op.drop_index(op.f('ix_crm_mensajes_estado'), table_name='crm_mensajes')
    op.drop_index(op.f('ix_crm_mensajes_contacto_referencia'), table_name='crm_mensajes')
    op.drop_index(op.f('ix_crm_mensajes_contacto_id'), table_name='crm_mensajes')
    op.drop_index(op.f('ix_crm_mensajes_canal'), table_name='crm_mensajes')
    op.create_index('idx_crm_mensajes_evento', 'crm_mensajes', ['evento_id'], unique=False)
    op.create_index('idx_crm_mensajes_estado_tipo', 'crm_mensajes', ['estado', 'tipo'], unique=False)
    op.create_index('idx_crm_mensajes_contacto', 'crm_mensajes', ['contacto_id'], unique=False)
    op.create_index('idx_crm_mensajes_canal_ref', 'crm_mensajes', ['canal', 'contacto_referencia'], unique=False)
    op.alter_column('crm_mensajes', 'fecha_mensaje',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('crm_mensajes', 'contenido',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('crm_mensajes', 'fecha_estado')
    op.drop_index(op.f('ix_crm_eventos_tipo_evento'), table_name='crm_eventos')
    op.create_index('idx_crm_eventos_tipo', 'crm_eventos', ['tipo_evento'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_crm_eventos_oportunidad', 'crm_eventos', ['oportunidad_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_crm_eventos_estado', 'crm_eventos', ['estado_evento'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('crm_eventos', 'resultado',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('crm_eventos', 'descripcion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('crm_contactos', sa.Column('necesidad', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('crm_contactos', sa.Column('tipo_operacion_interes_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('crm_contactos', sa.Column('estado_calificacion', sa.VARCHAR(length=20), server_default=sa.text("'nuevo'::character varying"), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_crm_contactos_tipo_operacion_interes', 'crm_contactos', 'crm_tipos_operacion', ['tipo_operacion_interes_id'], ['id'])
    op.create_index('idx_contacto_estado_calificacion', 'crm_contactos', ['estado_calificacion'], unique=False)
    op.drop_constraint('uq_cotizacion_monedas_fecha', 'cotizacion_moneda', type_='unique')
    op.create_unique_constraint('uq_cotizacion_moneda_fecha', 'cotizacion_moneda', ['moneda_origen_id', 'moneda_destino_id', 'fecha_vigencia'])
    op.create_table('vacancias_backup_20251116_231115',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('propiedad_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ciclo_activo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fecha_recibida', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('comentario_recibida', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fecha_en_reparacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('comentario_en_reparacion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fecha_disponible', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('comentario_disponible', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fecha_alquilada', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('comentario_alquilada', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fecha_retirada', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('comentario_retirada', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dias_reparacion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dias_disponible', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dias_totales', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('propiedades_backup_20251116_231630',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('propietario', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ambientes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metros_cuadrados', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('valor_alquiler', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('expensas', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fecha_ingreso', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('vencimiento_contrato', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('estado_fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('estado_comentario', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_table('vacancias_backup_20251116_231630',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('propiedad_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ciclo_activo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fecha_recibida', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('comentario_recibida', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fecha_en_reparacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('comentario_en_reparacion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fecha_disponible', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('comentario_disponible', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fecha_alquilada', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('comentario_alquilada', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fecha_retirada', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('comentario_retirada', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dias_reparacion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dias_disponible', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dias_totales', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('propiedades_backup_20251116_231115',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('propietario', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ambientes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metros_cuadrados', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('valor_alquiler', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('expensas', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fecha_ingreso', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('vencimiento_contrato', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('estado_fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('estado_comentario', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
