"""add_vacancia_and_update_propiedades

Revision ID: 623274e44549
Revises: 90f5f68df0bf
Create Date: 2025-11-14 19:57:27.025440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '623274e44549'
down_revision: Union[str, Sequence[str], None] = '90f5f68df0bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('propiedad_id', sa.Integer(), nullable=False),
    sa.Column('ciclo_activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_recibida', sa.DateTime(), nullable=True),
    sa.Column('comentario_recibida', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_en_reparacion', sa.DateTime(), nullable=True),
    sa.Column('comentario_en_reparacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_disponible', sa.DateTime(), nullable=True),
    sa.Column('comentario_disponible', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_alquilada', sa.DateTime(), nullable=True),
    sa.Column('comentario_alquilada', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_retirada', sa.DateTime(), nullable=True),
    sa.Column('comentario_retirada', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dias_reparacion', sa.Integer(), nullable=True),
    sa.Column('dias_disponible', sa.Integer(), nullable=True),
    sa.Column('dias_totales', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['propiedad_id'], ['propiedades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancias_propiedad_id'), 'vacancias', ['propiedad_id'], unique=False)
    op.add_column('propiedades', sa.Column('ambientes', sa.Integer(), nullable=True))
    op.add_column('propiedades', sa.Column('metros_cuadrados', sa.Float(), nullable=True))
    op.add_column('propiedades', sa.Column('valor_alquiler', sa.Float(), nullable=True))
    op.add_column('propiedades', sa.Column('expensas', sa.Float(), nullable=True))
    op.add_column('propiedades', sa.Column('fecha_ingreso', sa.Date(), nullable=True))
    op.add_column('propiedades', sa.Column('vencimiento_contrato', sa.Date(), nullable=True))
    
    # Agregar estado_fecha como nullable primero
    op.add_column('propiedades', sa.Column('estado_fecha', sa.DateTime(), nullable=True))
    
    # Poblar estado_fecha con la fecha actual para registros existentes
    op.execute("UPDATE propiedades SET estado_fecha = NOW() WHERE estado_fecha IS NULL")
    
    # Ahora hacerlo NOT NULL
    op.alter_column('propiedades', 'estado_fecha', nullable=False)
    
    op.add_column('propiedades', sa.Column('estado_comentario', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propiedades', 'estado_comentario')
    op.drop_column('propiedades', 'estado_fecha')
    op.drop_column('propiedades', 'vencimiento_contrato')
    op.drop_column('propiedades', 'fecha_ingreso')
    op.drop_column('propiedades', 'expensas')
    op.drop_column('propiedades', 'valor_alquiler')
    op.drop_column('propiedades', 'metros_cuadrados')
    op.drop_column('propiedades', 'ambientes')
    op.drop_index(op.f('ix_vacancias_propiedad_id'), table_name='vacancias')
    op.drop_table('vacancias')
    # ### end Alembic commands ###
