"""add_metodo_pago_tipo_compra_to_po_orders_and_fields_to_details

Revision ID: 851a0d1bd70b
Revises: c208dbf54d48
Create Date: 2026-02-08 12:14:41.166846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '851a0d1bd70b'
down_revision: Union[str, Sequence[str], None] = 'c208dbf54d48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('po_order_details', sa.Column('centro_costo_id', sa.Integer(), nullable=True))
    op.add_column('po_order_details', sa.Column('oportunidad_id', sa.Integer(), nullable=True))
    op.add_column('po_order_details', sa.Column('cantidad_facturada', sa.DECIMAL(precision=10, scale=3), server_default='0', nullable=False))
    op.create_foreign_key(None, 'po_order_details', 'crm_oportunidades', ['oportunidad_id'], ['id'])
    op.create_foreign_key(None, 'po_order_details', 'centros_costo', ['centro_costo_id'], ['id'])
    
    # Add metodo_pago_id as nullable first
    op.add_column('po_orders', sa.Column('metodo_pago_id', sa.Integer(), nullable=True))
    
    # Update existing records with default value (metodo_pago_id = 1)
    op.execute("UPDATE po_orders SET metodo_pago_id = 1 WHERE metodo_pago_id IS NULL")
    
    # Now make it NOT NULL
    op.alter_column('po_orders', 'metodo_pago_id', nullable=False)
    
    op.add_column('po_orders', sa.Column('tipo_compra', sa.String(length=20), server_default='normal', nullable=False))
    op.alter_column('po_orders', 'departamento_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'po_orders', 'metodos_pago', ['metodo_pago_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'po_orders', type_='foreignkey')
    op.alter_column('po_orders', 'departamento_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('po_orders', 'tipo_compra')
    op.drop_column('po_orders', 'metodo_pago_id')
    op.drop_constraint(None, 'po_order_details', type_='foreignkey')
    op.drop_constraint(None, 'po_order_details', type_='foreignkey')
    op.drop_column('po_order_details', 'cantidad_facturada')
    op.drop_column('po_order_details', 'oportunidad_id')
    op.drop_column('po_order_details', 'centro_costo_id')
    # ### end Alembic commands ###
