"""add centro_costo and update solicitudes

Revision ID: 90f5f68df0bf
Revises: b1d5f5c2279f
Create Date: 2025-11-12 05:19:57.023574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90f5f68df0bf'
down_revision: Union[str, Sequence[str], None] = 'b1d5f5c2279f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - Solo cambios de Centro de Costo."""
    # 1. Crear tabla centros_costo
    op.create_table('centros_costo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('codigo_contable', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_centros_costo_codigo_contable'), 'centros_costo', ['codigo_contable'], unique=False)
    op.create_index(op.f('ix_centros_costo_nombre'), 'centros_costo', ['nombre'], unique=True)
    op.create_index(op.f('ix_centros_costo_tipo'), 'centros_costo', ['tipo'], unique=False)
    
    # 2. Agregar campos a solicitud_detalles
    op.add_column('solicitud_detalles', sa.Column('precio', sa.DECIMAL(precision=15, scale=2), server_default='0', nullable=False))
    op.add_column('solicitud_detalles', sa.Column('importe', sa.DECIMAL(precision=15, scale=2), server_default='0', nullable=False))
    
    # 3. Agregar columna centro_costo_id como nullable primero
    op.add_column('solicitudes', sa.Column('centro_costo_id', sa.Integer(), nullable=True))
    
    # 4. Crear centro de costo por defecto
    op.execute("""
        INSERT INTO centros_costo (nombre, tipo, codigo_contable, descripcion, activo, created_at, updated_at, version)
        VALUES ('Sin Asignar', 'General', 'GEN-0000', 'Centro de costo por defecto para solicitudes sin asignar', TRUE, NOW(), NOW(), 1)
    """)
    
    # 5. Asignar el centro de costo por defecto (ID=1) a todas las solicitudes existentes
    op.execute("UPDATE solicitudes SET centro_costo_id = 1 WHERE centro_costo_id IS NULL")
    
    # 6. Hacer NOT NULL la columna centro_costo_id
    op.alter_column('solicitudes', 'centro_costo_id', nullable=False)
    
    # 7. Crear FK constraint
    op.create_foreign_key('fk_solicitudes_centro_costo', 'solicitudes', 'centros_costo', ['centro_costo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tipos_solicitud_nombre'), table_name='tipos_solicitud')
    op.create_index('ix_tipos_solicitud_nombre', 'tipos_solicitud', ['nombre'], unique=False)
    op.create_unique_constraint('tipos_solicitud_nombre_key', 'tipos_solicitud', ['nombre'])
    op.alter_column('tipos_solicitud', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('tipos_solicitud', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tipos_solicitud', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # Eliminar FK constraint de centro_costo_id
    op.drop_constraint('fk_solicitudes_centro_costo', 'solicitudes', type_='foreignkey')
    
    # Eliminar columna centro_costo_id de solicitudes
    op.drop_column('solicitudes', 'centro_costo_id')
    
    # Eliminar campos de solicitud_detalles
    op.drop_column('solicitud_detalles', 'importe')
    op.drop_column('solicitud_detalles', 'precio')
    
    # Eliminar índices de centros_costo
    op.drop_index(op.f('ix_centros_costo_tipo'), table_name='centros_costo')
    op.drop_index(op.f('ix_centros_costo_nombre'), table_name='centros_costo')
    op.drop_index(op.f('ix_centros_costo_codigo_contable'), table_name='centros_costo')
    
    # Eliminar tabla centros_costo
    op.drop_table('centros_costo')
    # ### end Alembic commands ###
