"""add centro_costo and update solicitudes

Revision ID: 90f5f68df0bf
Revises: b1d5f5c2279f
Create Date: 2025-11-12 05:19:57.023574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90f5f68df0bf'
down_revision: Union[str, Sequence[str], None] = 'b1d5f5c2279f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centros_costo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('codigo_contable', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_centros_costo_codigo_contable'), 'centros_costo', ['codigo_contable'], unique=False)
    op.create_index(op.f('ix_centros_costo_nombre'), 'centros_costo', ['nombre'], unique=True)
    op.create_index(op.f('ix_centros_costo_tipo'), 'centros_costo', ['tipo'], unique=False)
    op.drop_table('facturas_extracciones')
    op.drop_index('ix_clientes_cuit', table_name='clientes')
    op.drop_index('ix_clientes_razon_social', table_name='clientes')
    op.drop_table('clientes')
    op.add_column('comprobantes', sa.Column('metodo_extraccion', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('comprobantes', sa.Column('extractor_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('comprobantes', sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('comprobantes', sa.Column('proveedor_id', sa.Integer(), nullable=True))
    op.add_column('comprobantes', sa.Column('tipo_operacion_id', sa.Integer(), nullable=True))
    op.add_column('comprobantes', sa.Column('warnings', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('comprobantes', sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('departamentos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('departamentos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('departamentos', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint('departamentos_nombre_key', 'departamentos', type_='unique')
    op.drop_index('ix_departamentos_nombre', table_name='departamentos')
    op.create_index(op.f('ix_departamentos_nombre'), 'departamentos', ['nombre'], unique=True)
    op.drop_constraint('fk_nominas_proyectos_idproyecto', 'nominas', type_='foreignkey')
    op.create_foreign_key(None, 'nominas', 'proyectos', ['idproyecto'], ['id'])
    op.alter_column('proyectos', 'comentario',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.add_column('solicitud_detalles', sa.Column('precio', sa.DECIMAL(precision=15, scale=2), server_default='0', nullable=False))
    op.add_column('solicitud_detalles', sa.Column('importe', sa.DECIMAL(precision=15, scale=2), server_default='0', nullable=False))
    op.drop_index('idx_solicitud_detalles_articulo_id', table_name='solicitud_detalles')
    op.drop_index('idx_solicitud_detalles_solicitud_id', table_name='solicitud_detalles')
    
    # Agregar columna centro_costo_id como nullable primero
    op.add_column('solicitudes', sa.Column('centro_costo_id', sa.Integer(), nullable=True))
    
    # Crear centro de costo por defecto
    op.execute("""
        INSERT INTO centros_costo (nombre, tipo, codigo_contable, descripcion, activo, created_at, updated_at, version)
        VALUES ('Sin Asignar', 'General', 'GEN-0000', 'Centro de costo por defecto para solicitudes sin asignar', TRUE, NOW(), NOW(), 1)
    """)
    
    # Asignar el centro de costo por defecto (ID=1) a todas las solicitudes existentes
    op.execute("UPDATE solicitudes SET centro_costo_id = 1 WHERE centro_costo_id IS NULL")
    
    # Hacer NOT NULL la columna centro_costo_id
    op.alter_column('solicitudes', 'centro_costo_id', nullable=False)
    
    op.drop_index('idx_solicitudes_solicitante_id', table_name='solicitudes')
    op.create_foreign_key(None, 'solicitudes', 'centros_costo', ['centro_costo_id'], ['id'])
    op.alter_column('tipos_solicitud', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tipos_solicitud', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('tipos_solicitud', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint('tipos_solicitud_nombre_key', 'tipos_solicitud', type_='unique')
    op.drop_index('ix_tipos_solicitud_nombre', table_name='tipos_solicitud')
    op.create_index(op.f('ix_tipos_solicitud_nombre'), 'tipos_solicitud', ['nombre'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tipos_solicitud_nombre'), table_name='tipos_solicitud')
    op.create_index('ix_tipos_solicitud_nombre', 'tipos_solicitud', ['nombre'], unique=False)
    op.create_unique_constraint('tipos_solicitud_nombre_key', 'tipos_solicitud', ['nombre'])
    op.alter_column('tipos_solicitud', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('tipos_solicitud', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tipos_solicitud', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'solicitudes', type_='foreignkey')
    op.create_index('idx_solicitudes_solicitante_id', 'solicitudes', ['solicitante_id'], unique=False)
    op.drop_column('solicitudes', 'centro_costo_id')
    op.create_index('idx_solicitud_detalles_solicitud_id', 'solicitud_detalles', ['solicitud_id'], unique=False)
    op.create_index('idx_solicitud_detalles_articulo_id', 'solicitud_detalles', ['articulo_id'], unique=False)
    op.drop_column('solicitud_detalles', 'importe')
    op.drop_column('solicitud_detalles', 'precio')
    op.alter_column('proyectos', 'comentario',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'nominas', type_='foreignkey')
    op.create_foreign_key('fk_nominas_proyectos_idproyecto', 'nominas', 'proyectos', ['idproyecto'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_departamentos_nombre'), table_name='departamentos')
    op.create_index('ix_departamentos_nombre', 'departamentos', ['nombre'], unique=False)
    op.create_unique_constraint('departamentos_nombre_key', 'departamentos', ['nombre'])
    op.alter_column('departamentos', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('departamentos', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('departamentos', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('comprobantes', 'error')
    op.drop_column('comprobantes', 'warnings')
    op.drop_column('comprobantes', 'tipo_operacion_id')
    op.drop_column('comprobantes', 'proveedor_id')
    op.drop_column('comprobantes', 'estado')
    op.drop_column('comprobantes', 'extractor_version')
    op.drop_column('comprobantes', 'metodo_extraccion')
    op.create_table('clientes',
    sa.Column('razon_social', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cuit', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('direccion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('condicion_iva', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='clientes_pkey')
    )
    op.create_index('ix_clientes_razon_social', 'clientes', ['razon_social'], unique=False)
    op.create_index('ix_clientes_cuit', 'clientes', ['cuit'], unique=True)
    op.create_table('facturas_extracciones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('factura_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('archivo_nombre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('archivo_guardado', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('archivo_ruta', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metodo_extraccion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('extractor_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('proveedor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_operacion_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_pdf', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('payload_json', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('warnings', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('error', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], name='facturas_extracciones_factura_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='facturas_extracciones_pkey')
    )
    op.drop_index(op.f('ix_centros_costo_tipo'), table_name='centros_costo')
    op.drop_index(op.f('ix_centros_costo_nombre'), table_name='centros_costo')
    op.drop_index(op.f('ix_centros_costo_codigo_contable'), table_name='centros_costo')
    op.drop_table('centros_costo')
    # ### end Alembic commands ###
