"""Agregar FK oportunidad_id a po_ordenes_compra y po_facturas

Revision ID: d435230ca986
Revises: 20260125_add_default_articulos_to_proveedores
Create Date: 2026-01-26 08:10:35.970014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd435230ca986'
down_revision: Union[str, Sequence[str], None] = '20260125_add_default_articulos_to_proveedores'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('po_factura_impuestos')
    op.drop_index('idx_articulos_activo', table_name='articulos')
    op.drop_index('idx_articulos_generico', table_name='articulos')
    op.alter_column('crm_eventos', 'oportunidad_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('po_factura_detalles', sa.Column('oportunidad_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'po_factura_detalles', 'crm_oportunidades', ['oportunidad_id'], ['id'])
    op.alter_column('po_factura_totales', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_factura_totales', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_factura_totales', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('ix_po_factura_totales_centro_costo_id', table_name='po_factura_totales')
    op.drop_index('ix_po_factura_totales_concepto_id', table_name='po_factura_totales')
    op.drop_index('ix_po_factura_totales_factura_id', table_name='po_factura_totales')
    op.drop_index('ix_po_factura_totales_tipo', table_name='po_factura_totales')
    op.drop_constraint('uq_po_factura_totales_factura_tipo_concepto_centro', 'po_factura_totales', type_='unique')
    op.add_column('po_facturas', sa.Column('oportunidad_id', sa.Integer(), nullable=True))
    op.drop_index('idx_po_facturas_departamento_id', table_name='po_facturas')
    op.create_foreign_key(None, 'po_facturas', 'crm_oportunidades', ['oportunidad_id'], ['id'])
    op.add_column('po_orden_compra_detalles', sa.Column('oportunidad_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'po_orden_compra_detalles', 'crm_oportunidades', ['oportunidad_id'], ['id'])
    op.add_column('po_ordenes_compra', sa.Column('oportunidad_id', sa.Integer(), nullable=True))
    op.drop_index('idx_po_ordenes_compra_departamento_id', table_name='po_ordenes_compra')
    op.drop_index('idx_po_ordenes_compra_tipo_compra', table_name='po_ordenes_compra')
    op.create_foreign_key(None, 'po_ordenes_compra', 'crm_oportunidades', ['oportunidad_id'], ['id'])
    op.drop_index('idx_proveedores_default_departamento_id', table_name='proveedores')
    op.drop_index('idx_proveedores_default_tipo_solicitud_id', table_name='proveedores')
    op.drop_index('ix_proveedores_adm_concepto_id', table_name='proveedores')
    op.drop_index('ix_proveedores_default_articulos_id', table_name='proveedores')
    op.drop_constraint('fk_proveedores_default_articulos_id', 'proveedores', type_='foreignkey')
    op.create_foreign_key(None, 'proveedores', 'articulos', ['default_articulos_id'], ['id'])
    op.drop_index('idx_solicitudes_tipo_compra', table_name='solicitudes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_solicitudes_tipo_compra', 'solicitudes', ['tipo_compra'], unique=False)
    op.drop_constraint(None, 'proveedores', type_='foreignkey')
    op.create_foreign_key('fk_proveedores_default_articulos_id', 'proveedores', 'articulos', ['default_articulos_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_proveedores_default_articulos_id', 'proveedores', ['default_articulos_id'], unique=False)
    op.create_index('ix_proveedores_adm_concepto_id', 'proveedores', ['adm_concepto_id'], unique=False)
    op.create_index('idx_proveedores_default_tipo_solicitud_id', 'proveedores', ['default_tipo_solicitud_id'], unique=False)
    op.create_index('idx_proveedores_default_departamento_id', 'proveedores', ['default_departamento_id'], unique=False)
    op.drop_constraint(None, 'po_ordenes_compra', type_='foreignkey')
    op.create_index('idx_po_ordenes_compra_tipo_compra', 'po_ordenes_compra', ['tipo_compra'], unique=False)
    op.create_index('idx_po_ordenes_compra_departamento_id', 'po_ordenes_compra', ['departamento_id'], unique=False)
    op.drop_column('po_ordenes_compra', 'oportunidad_id')
    op.drop_constraint(None, 'po_orden_compra_detalles', type_='foreignkey')
    op.drop_column('po_orden_compra_detalles', 'oportunidad_id')
    op.drop_constraint(None, 'po_facturas', type_='foreignkey')
    op.create_index('idx_po_facturas_departamento_id', 'po_facturas', ['departamento_id'], unique=False)
    op.drop_column('po_facturas', 'oportunidad_id')
    op.create_unique_constraint('uq_po_factura_totales_factura_tipo_concepto_centro', 'po_factura_totales', ['factura_id', 'tipo', 'concepto_id', 'centro_costo_id'])
    op.create_index('ix_po_factura_totales_tipo', 'po_factura_totales', ['tipo'], unique=False)
    op.create_index('ix_po_factura_totales_factura_id', 'po_factura_totales', ['factura_id'], unique=False)
    op.create_index('ix_po_factura_totales_concepto_id', 'po_factura_totales', ['concepto_id'], unique=False)
    op.create_index('ix_po_factura_totales_centro_costo_id', 'po_factura_totales', ['centro_costo_id'], unique=False)
    op.alter_column('po_factura_totales', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('po_factura_totales', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_factura_totales', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'po_factura_detalles', type_='foreignkey')
    op.drop_column('po_factura_detalles', 'oportunidad_id')
    op.alter_column('crm_eventos', 'oportunidad_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('idx_articulos_generico', 'articulos', ['generico'], unique=False)
    op.create_index('idx_articulos_activo', 'articulos', ['activo'], unique=False)
    op.create_table('po_factura_impuestos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('tipo_impuesto', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('base_imponible', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('porcentaje', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('importe', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('es_retencion', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('es_percepcion', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('codigo_afip', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('numero_certificado', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('factura_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['po_facturas.id'], name='po_factura_impuestos_factura_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='po_factura_impuestos_pkey')
    )
    # ### end Alembic commands ###
