"""agregar_tipo_propiedad_id_fk_a_propiedades

Revision ID: e484951a2e2c
Revises: 9635faa590ee
Create Date: 2026-02-19 16:35:17.412144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e484951a2e2c'
down_revision: Union[str, Sequence[str], None] = '9635faa590ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('po_invoice_status_fin', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('po_invoice_status_fin', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('po_invoice_status_fin', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('ix_po_invoice_status_fin_nombre', table_name='po_invoice_status_fin')
    op.alter_column('po_invoice_taxes', 'importe_base',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.DECIMAL(precision=15, scale=2),
               nullable=False)
    op.alter_column('po_invoice_taxes', 'porcentaje',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.drop_index('ix_po_invoices_invoice_status_fin_id', table_name='po_invoices')
    op.add_column('propiedades', sa.Column('tipo_propiedad_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_propiedades_tipo_propiedad_id'), 'propiedades', ['tipo_propiedad_id'], unique=False)
    op.create_foreign_key(None, 'propiedades', 'tipos_propiedad', ['tipo_propiedad_id'], ['id'])
    op.alter_column('tax_profile_details', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tax_profile_details', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tax_profile_details', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('ix_tax_profile_details_deleted_at', table_name='tax_profile_details')
    op.drop_index('ix_tax_profile_details_profile_id', table_name='tax_profile_details')
    op.drop_constraint('tax_profile_details_updated_by_id_fkey', 'tax_profile_details', type_='foreignkey')
    op.drop_constraint('tax_profile_details_created_by_id_fkey', 'tax_profile_details', type_='foreignkey')
    op.drop_column('tax_profile_details', 'updated_by_id')
    op.drop_column('tax_profile_details', 'created_by_id')
    op.alter_column('tax_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tax_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tax_profiles', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('ix_tax_profiles_deleted_at', table_name='tax_profiles')
    op.drop_index('ix_tax_profiles_nombre', table_name='tax_profiles')
    op.drop_constraint('tax_profiles_created_by_id_fkey', 'tax_profiles', type_='foreignkey')
    op.drop_constraint('tax_profiles_updated_by_id_fkey', 'tax_profiles', type_='foreignkey')
    op.drop_column('tax_profiles', 'updated_by_id')
    op.drop_column('tax_profiles', 'created_by_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tax_profiles', sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tax_profiles', sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tax_profiles_updated_by_id_fkey', 'tax_profiles', 'users', ['updated_by_id'], ['id'])
    op.create_foreign_key('tax_profiles_created_by_id_fkey', 'tax_profiles', 'users', ['created_by_id'], ['id'])
    op.create_index('ix_tax_profiles_nombre', 'tax_profiles', ['nombre'], unique=False)
    op.create_index('ix_tax_profiles_deleted_at', 'tax_profiles', ['deleted_at'], unique=False)
    op.alter_column('tax_profiles', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('tax_profiles', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tax_profiles', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('tax_profile_details', sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tax_profile_details', sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tax_profile_details_created_by_id_fkey', 'tax_profile_details', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key('tax_profile_details_updated_by_id_fkey', 'tax_profile_details', 'users', ['updated_by_id'], ['id'])
    op.create_index('ix_tax_profile_details_profile_id', 'tax_profile_details', ['profile_id'], unique=False)
    op.create_index('ix_tax_profile_details_deleted_at', 'tax_profile_details', ['deleted_at'], unique=False)
    op.alter_column('tax_profile_details', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('tax_profile_details', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tax_profile_details', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'propiedades', type_='foreignkey')
    op.drop_index(op.f('ix_propiedades_tipo_propiedad_id'), table_name='propiedades')
    op.drop_column('propiedades', 'tipo_propiedad_id')
    op.create_index('ix_po_invoices_invoice_status_fin_id', 'po_invoices', ['invoice_status_fin_id'], unique=False)
    op.alter_column('po_invoice_taxes', 'porcentaje',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('po_invoice_taxes', 'importe_base',
               existing_type=sa.DECIMAL(precision=15, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.create_index('ix_po_invoice_status_fin_nombre', 'po_invoice_status_fin', ['nombre'], unique=False)
    op.alter_column('po_invoice_status_fin', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('po_invoice_status_fin', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('po_invoice_status_fin', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    # ### end Alembic commands ###
