"""make_po_invoice_detail_descripcion_nullable

Revision ID: 054f4b7e748c
Revises: 20260211_cleanup_po_invoice_detalles
Create Date: 2026-02-11 19:11:11.006236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '054f4b7e748c'
down_revision: Union[str, Sequence[str], None] = '20260211_cleanup_po_invoice_detalles'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('po_factura_totales')
    op.drop_table('po_factura_detalles')
    op.drop_table('po_facturas')
    op.alter_column('po_invoice_detalles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_invoice_detalles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_invoice_detalles', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('po_invoice_detalles', 'descripcion',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('po_invoice_detalles', 'cantidad',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               nullable=True)
    op.alter_column('po_invoice_detalles', 'precio_unitario',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=True)
    op.alter_column('po_invoice_detalles', 'importe',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.drop_constraint('po_invoice_detalles_invoice_id_fkey', 'po_invoice_detalles', type_='foreignkey')
    op.create_foreign_key(None, 'po_invoice_detalles', 'po_invoices', ['invoice_id'], ['id'])
    op.alter_column('po_invoice_status', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_invoice_status', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_invoice_status', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('ix_po_invoice_taxes_concepto_id', table_name='po_invoice_taxes')
    op.drop_index('ix_po_invoice_taxes_id', table_name='po_invoice_taxes')
    op.drop_index('ix_po_invoice_taxes_invoice_id', table_name='po_invoice_taxes')
    op.alter_column('po_invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_invoices', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('po_invoices', 'subtotal',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('po_invoices', 'total_impuestos',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('po_invoices', 'total',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('po_invoices', 'fecha_estado',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('ix_proveedores_tipo_comprobante_id', table_name='proveedores')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_proveedores_tipo_comprobante_id', 'proveedores', ['tipo_comprobante_id'], unique=False)
    op.alter_column('po_invoices', 'fecha_estado',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('po_invoices', 'total',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('po_invoices', 'total_impuestos',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('po_invoices', 'subtotal',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('po_invoices', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('po_invoices', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_invoices', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_po_invoice_taxes_invoice_id', 'po_invoice_taxes', ['invoice_id'], unique=False)
    op.create_index('ix_po_invoice_taxes_id', 'po_invoice_taxes', ['id'], unique=False)
    op.create_index('ix_po_invoice_taxes_concepto_id', 'po_invoice_taxes', ['concepto_id'], unique=False)
    op.alter_column('po_invoice_status', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('po_invoice_status', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_invoice_status', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'po_invoice_detalles', type_='foreignkey')
    op.create_foreign_key('po_invoice_detalles_invoice_id_fkey', 'po_invoice_detalles', 'po_invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.alter_column('po_invoice_detalles', 'importe',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('po_invoice_detalles', 'precio_unitario',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=False)
    op.alter_column('po_invoice_detalles', 'cantidad',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               nullable=False)
    op.alter_column('po_invoice_detalles', 'descripcion',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('po_invoice_detalles', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('po_invoice_detalles', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('po_invoice_detalles', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table('po_facturas',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('po_facturas_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('numero', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('punto_venta', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('id_tipocomprobante', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_emision', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fecha_vencimiento', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subtotal', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_impuestos', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('total', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('observaciones', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nombre_archivo_pdf', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('ruta_archivo_pdf', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('comprobante_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('proveedor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usuario_responsable_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('metodo_pago_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('centro_costo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_solicitud_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('departamento_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_compra', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('oportunidad_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['centro_costo_id'], ['centros_costo.id'], name='po_facturas_centro_costo_id_fkey'),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.id'], name='po_facturas_comprobante_id_fkey'),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], name='fk_po_facturas_departamento_id'),
    sa.ForeignKeyConstraint(['id_tipocomprobante'], ['tipos_comprobante.id'], name='po_facturas_id_tipocomprobante_fkey'),
    sa.ForeignKeyConstraint(['metodo_pago_id'], ['metodos_pago.id'], name='po_facturas_metodo_pago_id_fkey'),
    sa.ForeignKeyConstraint(['oportunidad_id'], ['crm_oportunidades.id'], name='po_facturas_oportunidad_id_fkey'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], name='po_facturas_proveedor_id_fkey'),
    sa.ForeignKeyConstraint(['tipo_solicitud_id'], ['tipos_solicitud.id'], name='po_facturas_tipo_solicitud_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_responsable_id'], ['users.id'], name='po_facturas_usuario_responsable_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='po_facturas_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('po_factura_detalles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('codigo_producto', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('unidad_medida', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('precio_unitario', sa.NUMERIC(precision=15, scale=4), autoincrement=False, nullable=True),
    sa.Column('subtotal', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('porcentaje_descuento', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('importe_descuento', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('porcentaje_iva', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('importe_iva', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_linea', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('orden', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('factura_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('centro_costo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('articulo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('oportunidad_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos.id'], name='fk_po_factura_detalles_articulo'),
    sa.ForeignKeyConstraint(['centro_costo_id'], ['centros_costo.id'], name='po_factura_detalles_centro_costo_id_fkey'),
    sa.ForeignKeyConstraint(['factura_id'], ['po_facturas.id'], name='po_factura_detalles_factura_id_fkey'),
    sa.ForeignKeyConstraint(['oportunidad_id'], ['crm_oportunidades.id'], name='po_factura_detalles_oportunidad_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='po_factura_detalles_pkey')
    )
    op.create_table('po_factura_totales',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('factura_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('concepto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('centro_costo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('importe', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['centro_costo_id'], ['centros_costo.id'], name='po_factura_totales_centro_costo_id_fkey'),
    sa.ForeignKeyConstraint(['concepto_id'], ['adm_conceptos.id'], name='po_factura_totales_concepto_id_fkey'),
    sa.ForeignKeyConstraint(['factura_id'], ['po_facturas.id'], name='po_factura_totales_factura_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='po_factura_totales_pkey')
    )
    # ### end Alembic commands ###
