"""add_centro_costo_fk_to_departamentos

Revision ID: bb6d8563b4bb
Revises: d435230ca986
Create Date: 2026-01-28 20:23:01.611601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb6d8563b4bb'
down_revision: Union[str, Sequence[str], None] = 'd435230ca986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departamentos', sa.Column('centro_costo_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_departamentos_centro_costo_id', 'departamentos', 'centros_costo', ['centro_costo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_departamentos_centro_costo_id', 'departamentos', type_='foreignkey')
    op.drop_column('departamentos', 'centro_costo_id')
    # ### end Alembic commands ###
