"""remove discount and tax fields from po_orden_compra_detalles

Revision ID: cea3112b5aaf
Revises: 3460bb40d6db
Create Date: 2026-02-04 01:48:29.767910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea3112b5aaf'
down_revision: Union[str, Sequence[str], None] = '3460bb40d6db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('po_orden_compra_detalles', 'importe_iva')
    op.drop_column('po_orden_compra_detalles', 'porcentaje_descuento')
    op.drop_column('po_orden_compra_detalles', 'importe_descuento')
    op.drop_column('po_orden_compra_detalles', 'porcentaje_iva')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('po_orden_compra_detalles', sa.Column('porcentaje_iva', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('po_orden_compra_detalles', sa.Column('importe_descuento', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('po_orden_compra_detalles', sa.Column('porcentaje_descuento', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('po_orden_compra_detalles', sa.Column('importe_iva', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
