"""add celular_id to users

Revision ID: add_celular_id_users  
Revises: 
Create Date: 2026-03-07 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_celular_id_users'
down_revision: Union[str, None] = None  # Actualizar con la última migración
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('celular_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_celular_id'), 'users', ['celular_id'], unique=False)
    op.create_foreign_key('fk_users_celular_id_crm_celulares', 'users', 'crm_celulares', ['celular_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_celular_id_crm_celulares', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_celular_id'), table_name='users')
    op.drop_column('users', 'celular_id')
    # ### end Alembic commands ###