"""initial migration

Revision ID: c0cb19ea7b37
Revises: 
Create Date: 2025-11-26 00:41:54.218631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0cb19ea7b37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('webhook_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('meta_app_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('meta_access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('meta_webhook_verify_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_nombre'), 'empresas', ['nombre'], unique=False)
    op.create_table('celulares',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('empresa_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meta_phone_number_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('waba_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estado_desde', sa.DateTime(), nullable=False),
    sa.Column('limite_mensual', sa.Integer(), nullable=True),
    sa.Column('ultimo_token_valido', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_celulares_empresa_id'), 'celulares', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_celulares_meta_phone_number_id'), 'celulares', ['meta_phone_number_id'], unique=False)
    op.create_table('contactos',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('empresa_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pais', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contactos_empresa_id'), 'contactos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_contactos_telefono'), 'contactos', ['telefono'], unique=False)
    op.create_table('plantillas_meta',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('empresa_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('idioma', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estado_meta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ultima_revision', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plantillas_meta_empresa_id'), 'plantillas_meta', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_plantillas_meta_nombre'), 'plantillas_meta', ['nombre'], unique=False)
    op.create_table('webhook_eventos',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('empresa_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tipo_evento', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meta_entry_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('procesado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_eventos_empresa_id'), 'webhook_eventos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_webhook_eventos_meta_entry_id'), 'webhook_eventos', ['meta_entry_id'], unique=False)
    op.create_table('conversaciones',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('empresa_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('contacto_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('celular_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('canal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contexto_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['celular_id'], ['celulares.id'], ),
    sa.ForeignKeyConstraint(['contacto_id'], ['contactos.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversaciones_celular_id'), 'conversaciones', ['celular_id'], unique=False)
    op.create_index(op.f('ix_conversaciones_contacto_id'), 'conversaciones', ['contacto_id'], unique=False)
    op.create_index(op.f('ix_conversaciones_empresa_id'), 'conversaciones', ['empresa_id'], unique=False)
    op.create_table('logs_integracion',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('empresa_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('celular_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('intent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('resultado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['celular_id'], ['celulares.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_integracion_empresa_id'), 'logs_integracion', ['empresa_id'], unique=False)
    op.create_table('mensajes',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('conversacion_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('empresa_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('celular_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('contacto_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('meta_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contenido', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('meta_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['celular_id'], ['celulares.id'], ),
    sa.ForeignKeyConstraint(['contacto_id'], ['contactos.id'], ),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversaciones.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajes_celular_id'), 'mensajes', ['celular_id'], unique=False)
    op.create_index(op.f('ix_mensajes_contacto_id'), 'mensajes', ['contacto_id'], unique=False)
    op.create_index(op.f('ix_mensajes_conversacion_id'), 'mensajes', ['conversacion_id'], unique=False)
    op.create_index(op.f('ix_mensajes_empresa_id'), 'mensajes', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_mensajes_meta_message_id'), 'mensajes', ['meta_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensajes_meta_message_id'), table_name='mensajes')
    op.drop_index(op.f('ix_mensajes_empresa_id'), table_name='mensajes')
    op.drop_index(op.f('ix_mensajes_conversacion_id'), table_name='mensajes')
    op.drop_index(op.f('ix_mensajes_contacto_id'), table_name='mensajes')
    op.drop_index(op.f('ix_mensajes_celular_id'), table_name='mensajes')
    op.drop_table('mensajes')
    op.drop_index(op.f('ix_logs_integracion_empresa_id'), table_name='logs_integracion')
    op.drop_table('logs_integracion')
    op.drop_index(op.f('ix_conversaciones_empresa_id'), table_name='conversaciones')
    op.drop_index(op.f('ix_conversaciones_contacto_id'), table_name='conversaciones')
    op.drop_index(op.f('ix_conversaciones_celular_id'), table_name='conversaciones')
    op.drop_table('conversaciones')
    op.drop_index(op.f('ix_webhook_eventos_meta_entry_id'), table_name='webhook_eventos')
    op.drop_index(op.f('ix_webhook_eventos_empresa_id'), table_name='webhook_eventos')
    op.drop_table('webhook_eventos')
    op.drop_index(op.f('ix_plantillas_meta_nombre'), table_name='plantillas_meta')
    op.drop_index(op.f('ix_plantillas_meta_empresa_id'), table_name='plantillas_meta')
    op.drop_table('plantillas_meta')
    op.drop_index(op.f('ix_contactos_telefono'), table_name='contactos')
    op.drop_index(op.f('ix_contactos_empresa_id'), table_name='contactos')
    op.drop_table('contactos')
    op.drop_index(op.f('ix_celulares_meta_phone_number_id'), table_name='celulares')
    op.drop_index(op.f('ix_celulares_empresa_id'), table_name='celulares')
    op.drop_table('celulares')
    op.drop_index(op.f('ix_empresas_nombre'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
