"""
Resumen de validaciones del modelo CRMEvento
"""

print("\n" + "="*80)
print("VALIDACIONES DEL MODELO CRMEvento")
print("="*80 + "\n")

print("✅ CAMPOS OBLIGATORIOS (NOT NULL):")
print("-" * 80)
print("1. oportunidad_id    : int      - FK a crm_oportunidades (índice)")
print("2. titulo            : str      - Título del evento (max 255 chars)")
print("3. tipo_evento       : str      - Tipo: llamada|reunion|visita|email|whatsapp|otro")
print("4. fecha_evento      : datetime - Fecha/hora programada o realizada (índice)")
print("5. estado_evento     : str      - Estado: 1-pendiente|2-realizado|3-cancelado|4-reagendar")
print("6. asignado_a_id     : int      - FK a users (responsable)")
print()

print("📋 CAMPOS OPCIONALES:")
print("-" * 80)
print("1. resultado         : str|None - Resultado/notas del evento")
print()

print("🔍 RESTRICCIONES EN BASE DE DATOS:")
print("-" * 80)
print("- oportunidad_id: NOT NULL + FK constraint + índice")
print("- titulo: NOT NULL")
print("- tipo_evento: NOT NULL + índice")
print("- fecha_evento: NOT NULL + índice")
print("- estado_evento: NOT NULL + índice")
print("- asignado_a_id: NOT NULL + FK constraint")
print()

print("🎯 VALORES POR DEFECTO:")
print("-" * 80)
print("- estado_evento: '1-pendiente' (EstadoEvento.PENDIENTE)")
print()

print("📊 ÍNDICES CREADOS:")
print("-" * 80)
print("- idx_crm_eventos_oportunidad (oportunidad_id) WHERE deleted_at IS NULL")
print("- idx_crm_eventos_tipo (tipo_evento) WHERE deleted_at IS NULL")
print("- idx_crm_eventos_estado (estado_evento) WHERE deleted_at IS NULL")
print()

print("="*80)
print("✅ TODOS LOS EVENTOS DEBEN TENER:")
print("="*80)
print("1. ✓ Oportunidad vinculada (oportunidad_id)")
print("2. ✓ Título descriptivo")
print("3. ✓ Tipo de evento definido")
print("4. ✓ Fecha del evento")
print("5. ✓ Responsable asignado")
print("6. ✓ Estado (por defecto: pendiente)")
print("="*80 + "\n")
