"""add pais relationship and fix models

Revision ID: cb323d3d9b59
Revises: 9e55ba6106da
Create Date: 2025-09-03 01:04:03.007467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb323d3d9b59'
down_revision: Union[str, Sequence[str], None] = '9e55ba6106da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Solo los cambios compatibles con SQLite
    # Usar batch mode para agregar la foreign key en SQLite
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_users_pais_id', 'paises', ['pais_id'], ['id'])
    # --- Insertar dos países y asignar a usuarios ---
    conn = op.get_bind()
    # Insertar países de forma robusta
    conn.execute(sa.text("INSERT OR IGNORE INTO paises (name) VALUES ('Argentina')"))
    conn.execute(sa.text("INSERT OR IGNORE INTO paises (name) VALUES ('Brasil')"))
    # Obtener los IDs de los países
    result = conn.execute(sa.text("SELECT id FROM paises WHERE name IN ('Argentina', 'Brasil') ORDER BY id ASC"))
    pais_ids = [row[0] for row in result]
    # Obtener los usuarios
    usuarios = conn.execute(sa.text("SELECT id FROM users ORDER BY id ASC")).fetchall()
    # Asignar alternadamente los países a los usuarios
    for idx, usuario in enumerate(usuarios):
        pais_id = pais_ids[idx % len(pais_ids)]
        conn.execute(sa.text("UPDATE users SET pais_id = :pais_id WHERE id = :user_id"), {"pais_id": pais_id, "user_id": usuario[0]})
    # --- Insertar dos países y asignar a usuarios ---
    bind = op.get_bind()
    conn = bind.connect()
    # Insertar países
    conn.execute(sa.text("INSERT INTO paises (name) VALUES ('Argentina')"))
    conn.execute(sa.text("INSERT INTO paises (name) VALUES ('Brasil')"))
    # Obtener los IDs de los países
    result = conn.execute(sa.text("SELECT id FROM paises ORDER BY id ASC LIMIT 2"))
    pais_ids = [row[0] for row in result]
    # Obtener los usuarios
    usuarios = conn.execute(sa.text("SELECT id FROM users ORDER BY id ASC")).fetchall()
    # Asignar alternadamente los países a los usuarios
    for idx, usuario in enumerate(usuarios):
        pais_id = pais_ids[idx % 2]
        conn.execute(sa.text(f"UPDATE users SET pais_id = :pais_id WHERE id = :user_id"), {"pais_id": pais_id, "user_id": usuario[0]})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('users', 'pais_id')
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('stock', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
